version: 1.0.0.{build}


install:
    - git clone https://github.com/PowerShell/DscResource.Tests

    - npm --silent install

    - ps: |
        $moduleName = 'PowershellAPITest'
        $mainModuleFolder = "\"

        Install-Module ReverseDSC -MinimumVersion 1.9.2.11 -Force
        Install-Module MSOnline -MinimumVersion 1.1.183.17 -Force

        $webClient = new-object System.Net.WebClient
        $url = "https://download.microsoft.com/download/0/2/E/02E7E5BA-2190-44A8-B407-BC73CA0D6B87/SharePointOnlineManagementShell_8812-1200_x64_en-us.msi"
        $path = $PSScriptRoot + "\SharePointOnlineManagementShell_8316-1200_x64_en-us.msi"
        $webClient.DownloadFile($url, $path)
        msiexec /i $path /quiet /qn /norestart

        Install-Module Microsoft.Online.SharePoint.PowerShell -MinimumVersion 16.0.8316.0 -Force
        Import-Module Microsoft.Online.SharePoint.PowerShell -Force
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

build: off

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Harness' `
            -MainModulePath $mainModuleFolder `
            -CodeCovIo

after_test:
    - ps: |
        Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -MainModulePath $mainModuleFolder `
            -ResourceModuleName $moduleName
