version: 1.0.0.{build}


install:
    - git clone https://github.com/PowerShell/DscResource.Tests

    - npm --silent install

    - ps: |
        $moduleName = 'PowershellAPITest'
        $mainModuleFolder = "\"


        Install-Module Microsoft.Online.SharePoint.PowerShell -MinimumVersion 16.0.8316.0 -Force
        Import-Module Microsoft.Online.SharePoint.PowerShell -Force
        Import-Module -Name "$env:APPVEYOR_BUILD_FOLDER\DscResource.Tests\AppVeyor.psm1"
        Invoke-AppveyorInstallTask

build: off

test_script:
    - ps: |
        Invoke-AppveyorTestScriptTask `
            -Type 'Harness' `
            -MainModulePath $mainModuleFolder `
            -CodeCovIo

after_test:
    - ps: |
        Invoke-AppveyorAfterTestTask `
            -Type 'Wiki' `
            -MainModulePath $mainModuleFolder `
            -ResourceModuleName $moduleName
